feat: add controllers for items and users and all other functionalities
farukshin-n/sprint_13 pull request #1
Opened 2022-10-06 16:15 UTC by farukshin-n

2022-10-07 15:07 UTC, alexache requested changes

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public Item update(Item item) {
Не очень понятно, какое отношение имеет обновление объекта класса Item к классу ItemDto, в котором это написано? Такой помеси не должно быть

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestBody ItemDto itemDto) {
Не нужно ли и десь валидировать объект?

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank(message = "Item name cannot be blank")
Не очень понятно. зачем валидации на объекте для хранения

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (userRepository.getAllUsers().contains(userRepository.getUser(id))) {
Какая-та запутанная проверка, зачем этот поиск объекта в списке? Чем userRepository.getUser(id) != null недостаточное условие?

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public ItemDto createItem(Long id, ItemDto itemDto) {
Лучше иметь более осмысленное название аргумента - userId? ownerId? itemId?

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private List<ItemDto> listItemToListItemDto(List<Item> items) {
С функциональным подходом этот метод и вовсе не нужен с items.stream().map(ItemMapper::itemToDto).collect(Collectors.toList());

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    public User update(User user) {
Такой же комментарий. как и для ItemDto

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotBlank(message = "Name cannot be blank", groups = {Create.class})
и тут похожий комментарий - для чего эти валидации?

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +            Stream<Item> searchItemInName = items.values().stream()
Почему оба поиска не сделать одним проходом с фильтром, в котором будет поиск и по описанию и по названию?

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            itemRepository.addItem(item);
Логично использовать тот объект Item, который возвращается из репозитория. Сейчас это не настолько важно, но лучше правильно использовать интерфейс, мы вель "не знаем", как реализация сохраняет айди

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        final List<User> userList = userRepository.getAllUsers();
Лучше в функциональном стиле

2022-10-07 15:07 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public UserServiceImpl(UserRepository userRepository) {
Почему не RequiredArgsConstructor?

2022-10-07 22:21 UTC, farukshin-n commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            itemRepository.addItem(item);
Это же метод сохранения item, его в репозитории ещё нет. Или я чего-то не понял?

2022-10-07 22:24 UTC, farukshin-n commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public UserServiceImpl(UserRepository userRepository) {
Разумно, ступил)

2022-10-07 22:25 UTC, farukshin-n commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        final List<User> userList = userRepository.getAllUsers();
Сделал

2022-10-07 22:25 UTC, farukshin-n commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +            Stream<Item> searchItemInName = items.values().stream()
Попытался реализовать

2022-10-08 08:17 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            itemRepository.addItem(item);
Не понял, тут же вызывается itemRepository.addItem, который возвращает объект Item

2022-10-08 08:32 UTC, alexache approved these changes

2022-10-08 08:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Stream<ItemDto> searchItem(@RequestParam String text) {
Stream тут. пожалуй, ни к чему, это все же контроллер, а не интерфейс в библиотеке

2022-10-08 08:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +                items.values().stream().filter(item -> isItemAvailableAndHasText(item, textForSearch));
Все же лучше сразу и вызывать коллектор в конце обработки, и не очень понимаю, зачем отдельный метод на такую простую проверку.
`items.values().stream().filter(Item::isAvailable).filter(i -> i.getName().toLowerCase().contains(textForSearch) || i.getDescription().toLowerCase().contains(textForSearch)).collect(Collectors.toList())`
Если еще правильно раставить переносы строк. то такая фильтрация понятна с первого взгляда без необходимости вникать в еще один метод.
Основная цель стримов в джаве, как по мне, как раз улучшение читаемости такого рода кода

2022-10-08 08:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public Item update(ItemDto itemDto) {
Я и не это имел в виду, Такое обновление объекта вещи происходит буквально в одном месте. то есть там и можно написать эту логику. Больше нигде это и не требуется

2022-10-08 08:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public Stream<UserDto> getAllUsers() {
Здесь я опять же не о возвращении Stream говорил, а просто про использование стрима для вызова маппинга модели в дто объекты

2022-10-08 08:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private long ownerId;
Почему бы здесь и не хранить объект User?

2022-10-08 15:41 UTC, farukshin-n commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private long ownerId;
Моя мысль была в том, чтобы если какая-то информация в юзере изменится (вероятно, текущие тесты этого не предусматривают, этого я не знаю, но в принципе же такое возможно?), не менять её в каждом айтеме вслед за этим.

2022-10-17 10:16 UTC, merged