Add bookings #1
farukshin-n/sprint_13 pull request #2
Opened 2022-10-20 16:56 UTC by farukshin-n

2022-10-22 09:35 UTC, alexache requested changes

2022-10-22 09:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
Тут все выглядит хорошо :)

2022-10-22 09:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new IllegalArgumentException();
Лучше бы добавить немного деталей о сути ошибки

2022-10-22 09:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                commentRepository.findCommentsByItem_Id(item.getId())
Совсем незначительный комментарий: возможно лучше вынести стрим за пределы аргументов метода

2022-10-22 09:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                        commentRepository
Тут получается довольно много разных вызовов к БД, которые можно было бы объединить через запросы к репозиторию сразу со списком вещей, например. Каждый запрос довольно дорогой

2022-10-22 09:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +public interface ItemRequestService {
Кажется этот и соседний класс не нужны?

2022-10-24 21:29 UTC, alexache approved these changes

2022-10-24 21:29 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Optional<Booking>> getPastOrCurrentBookingByItemIdIn(Set<Long> itemIds);
Меня немного смущает, когда я вижу список опшиналов. Какое поведение тут ожидается?

2022-10-24 22:09 UTC, farukshin-n commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Optional<Booking>> getPastOrCurrentBookingByItemIdIn(Set<Long> itemIds);
Это я в поисках решения чуть-чуть сошёл с ума) На самом деле этот запросный метод не нужен, и опшионалы в нём тоже, удалю всё.

2022-10-24 22:10 UTC, merged

2022-10-24 22:26 UTC, farukshin-n commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Optional<Booking>> getPastOrCurrentBookingByItemIdIn(Set<Long> itemIds);
Optional тут на случай, если у item'а не будет ни одной booking'a. Тогда в методе getItemDtoWithBookingsAndComments не будет NPE при сборке объекта ItemDtoWithBookingsAndComments, который этот метод возвращает, просто в объекте будет два null'a вместо lastbooking & nextbooking.

P.S. прежний комментарий удалил, можно на него не обращать внимания: думал, что не удалил лишние запросные методы, которые были похожи на этот.