feat: resolve sprint 15
farukshin-n/sprint_13 pull request #3
Opened 2022-10-26 16:10 UTC by farukshin-n

2022-10-28 10:17 UTC, alexache requested changes

2022-10-28 10:17 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(defaultValue = "0") @PositiveOrZero final int from,
Нет смысла явно делать аргументы финальными, они effectively final

2022-10-28 10:17 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@EqualsAndHashCode
А для чего эта аннотация на модели? Используешь ли ты Сеты или сравнения целых обхектов?

2022-10-28 10:17 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +    List<ItemRequestDtoWithItems> getRequests(long id);
В интерфейсе тоже лучше писать полноценные названия переменных userId вместо id

2022-10-28 10:17 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        log.info(String.format("New itemrequest with id %d created successfully.", newItemRequest.getId()));
SLF4j logger тоже иметь возможность использования плейсхолдеров, поэтому еще и String.format лишний.
log.info("New itemrequest with id {} created successfully.", newItemRequest.getId())

2022-10-28 10:17 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                .map(itemRequest -> ItemRequestMapper.itemRequestToDtoWithItems(
Очень плохой вариант в цикле вызывать новые запросы к базе. Более правильный способ: собрать список реквест айди и одним запросом найти все вещи с такими реквест айди. getItemsByRequestIdIn(List<Long> requestIds)

2022-10-28 10:17 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                        itemRequest, getItemsByRequestId(itemRequest.getId())))
Такой же комментарий, как и выше

2022-10-28 10:17 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                new ArrayList<>(itemRepository.findByRequestIdOrderById(requestId))
Зачем новый лист?

2022-10-28 10:17 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    ObjectMapper mapper;
Модификаторы доступа не помешают

2022-10-28 10:17 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    BookingRepository mockBookingRepository;
Модификаторы доступа у полей все же нужны

2022-10-28 10:17 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +    ObjectMapper mapper;
Модификаторы полей

2022-10-28 10:17 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    }
Можно еще ставить verify на то, что мок сервиса был действительно вызван и указать ожидаемое количество раз его вызова (1)

2022-10-28 13:12 UTC, farukshin-n commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@EqualsAndHashCode
Да, это лишняя штука, которая осталась от предыдущих версий работы, забыл убрать, поправлю.

2022-10-29 09:53 UTC, alexache approved these changes

2022-10-29 09:53 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/model/User.java
>  @EqualsAndHashCode
Ни в одной модели (котрые хранятся в базе) не должно остаться @EqualsAndHashCode

2022-10-29 09:53 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +@SpringBootTest
Этот интеграционный тест можно было сделать в дополнение к существующему на сервис, а не заменять все методы. Хотя ТЗ и не уточняет, но в идеале было бы иметь еще более обширное покрытие, начиная со входящего запроса и проверяя состояние базы.
Сейчас исправлять уже не нужно, это тоже подвид интеграционного теста, так что в этом плане все ок :)

2022-10-29 11:24 UTC, merged